name: 'debug-action'
description: 'Outputs debug information'
author: 'saptak'
inputs:
  amazing-creature:
    description: What kind of amazing creature are you?
    default: person
runs:
  using: 'node12'
  main: './debug.js'